# Generated by Django 5.0.7 on 2024-07-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='member',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
            preserve_default=False,
        ),
    ]
