# Generated by Django 5.0.7 on 2024-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_foodimage_user_remove_meal_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='member',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='member',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
