# Generated by Django 5.0.7 on 2024-07-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_foodimage_member_remove_meal_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_type',
            new_name='meal_time',
        ),
    ]
