# Generated by Django 5.0.7 on 2024-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_meal_member_email_meal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='calories',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='carbs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='fat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='protein',
            field=models.CharField(max_length=50),
        ),
    ]
