# Generated by Django 5.0.7 on 2024-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('medical_history', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
