# Generated by Django 5.0.7 on 2024-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_memberprofile_userprofile_delete_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
