# Generated by Django 5.0.7 on 2024-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_memberprofile_email_memberprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
