# Generated by Django 5.0.7 on 2024-08-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_memberprofile_user_memberprofile_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='user_id',
        ),
    ]
